Feature/initial
CorneliusMoe/personal-website pull request #1
Opened 2023-05-10 17:11 UTC by CorneliusMoe

add initial framework for my personal website 

pls review :)

2023-05-10 19:36 UTC, NilsOt1 commented on index.html
> +    <footer></footer>
Da der noch leer ist, würde ich den raus lassen

2023-05-10 19:37 UTC, NilsOt1 approved these changes
Sieht gut aus! :)

2023-05-10 20:11 UTC, josch87 requested changes
Looks good, just would suggest to remove the buttons in nav.

2023-05-10 20:11 UTC, josch87 commented on index.html
> +        <button><a href="#aboutme">About me</a></button>
I suggest using a-elements only. Buttons should be used for actions only (see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#:~:text=Once%20activated%2C%20it%20then%20performs%20an%20action%2C%20such%20as%20submitting%20a%20form%20or%20opening%20a%20dialog.))

2023-05-11 06:35 UTC, makitango commented on index.html
> +        <button><a href="#aboutme">About me</a></button>
I also used buttons, but only for highlighting the linking to a different section.

I would suggest removing the buttons (have to do it myself also) and highlighting potential links to other sections using mouseover font changes.

Could be done in a follow-up commit though.

2023-05-11 06:36 UTC, makitango commented on index.html
> +    <footer></footer>
Could be a placeholder. In case of placeholders, a placeholder element/image could be used.

Though it doesn't affect the result here, so I wouldn't see it as critical.

2023-05-11 06:37 UTC, makitango approved these changes

2023-05-11 07:12 UTC, CorneliusMoe commented on index.html
> +        <button><a href="#aboutme">About me</a></button>
Done, thx for feedback

2023-05-11 15:44 UTC, merged